In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("shop_smart_ecommerce.csv")
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [3]:
df.head(70)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.000000,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.000000,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.000000,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,3,87.833333,0,0.0,27,798.333333,0.000000,0.012644,22.916036,0.8,Feb,2,2,3,1,Returning_Visitor,False,True
66,4,44.000000,0,0.0,90,6951.972222,0.002151,0.015013,0.000000,0.0,Feb,4,1,1,3,Returning_Visitor,False,False
67,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.6,Feb,2,2,5,1,Returning_Visitor,False,False
68,0,0.000000,0,0.0,18,902.000000,0.000000,0.007407,0.000000,0.0,Feb,2,7,2,4,Returning_Visitor,False,False
69,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.2,Feb,3,2,3,3,Returning_Visitor,False,False

In [4]:
#Encoding

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder()
df["Weekend"]=le.fit_transform(df["Weekend"])
df["Revenue"]=le.fit_transform(df["Revenue"])

ohe = OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore")
df["Month"]=ohe.fit_transform(df[["Month"]])
df["VisitorType"]=ohe.fit_transform(df[["VisitorType"]])

In [5]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,0.0,1,1,1,1,0.0,0,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,0.0,2,2,1,2,0.0,0,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,0.0,4,1,9,3,0.0,0,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,0.0,3,2,2,4,0.0,0,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,0.0,3,3,1,4,0.0,1,0

In [6]:
#Split Data
X=df.drop(columns=["Revenue"])
X
y=df["Revenue"]

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [8]:
#Decision_Tree
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [9]:
y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score

acc=accuracy_score(y_test, y_pred)
acc

0.8527893831408209

In [10]:
#Pre-Prunning
max_depths = [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20]
for depth in max_depths:
    model=tree.DecisionTreeClassifier(max_depth=depth)
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(f"for depth={depth}, accuracy={acc}")
 #Best is depth 4

for depth=2, accuracy=0.8849840255591054
for depth=3, accuracy=0.8869501105922831
for depth=4, accuracy=0.8916195625460801
for depth=5, accuracy=0.8908822806586385
for depth=6, accuracy=0.8908822806586385
for depth=7, accuracy=0.8871958712214303
for depth=8, accuracy=0.8827721798967806
for depth=9, accuracy=0.8817891373801917
for depth=10, accuracy=0.8778569673138363
for depth=12, accuracy=0.871712951585156
for depth=14, accuracy=0.8633570901941509
for depth=16, accuracy=0.8626198083067093
for depth=18, accuracy=0.856475792578029
for depth=20, accuracy=0.8537724256574096

In [11]:

min_samples_split = [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20]
best_acc = 0
best_split = None
for mini in min_samples_split:
    model=tree.DecisionTreeClassifier(max_depth=4,min_samples_split=mini)
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    if acc > best_acc:
        best_acc = acc
        best_split = mini

    print(f"For min_samples_split = {mini}, accuracy = {acc}")

print("Best min_samples_split:", best_split)
print("Best accuracy:", best_acc)

For min_samples_split = 2, accuracy = 0.8916195625460801
For min_samples_split = 3, accuracy = 0.8916195625460801
For min_samples_split = 4, accuracy = 0.8916195625460801
For min_samples_split = 5, accuracy = 0.8916195625460801
For min_samples_split = 6, accuracy = 0.8916195625460801
For min_samples_split = 7, accuracy = 0.8916195625460801
For min_samples_split = 8, accuracy = 0.8916195625460801
For min_samples_split = 9, accuracy = 0.8916195625460801
For min_samples_split = 10, accuracy = 0.8916195625460801
For min_samples_split = 12, accuracy = 0.8916195625460801
For min_samples_split = 14, accuracy = 0.8916195625460801
For min_samples_split = 16, accuracy = 0.8916195625460801
For min_samples_split = 18, accuracy = 0.8916195625460801
For min_samples_split = 20, accuracy = 0.8916195625460801
Best min_samples_split: 2
Best accuracy: 0.8916195625460801

In [12]:
from sklearn import tree

min_samples_leaf = [2,3,4,5,6,7,8,9,10,12,14,16,18,20]

best_acc = 0
best_leaf = None

for leaf in min_samples_leaf:
    model = tree.DecisionTreeClassifier(
        max_depth=4,
        min_samples_split=2,
        min_samples_leaf=leaf
    )

    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)

    if acc > best_acc:
        best_acc = acc
        best_leaf = leaf

    print(f"For min_samples_leaf = {leaf}, accuracy = {acc}")

print("Best min_samples_leaf:", best_leaf)
print("Best accuracy:", best_acc)

For min_samples_leaf = 2, accuracy = 0.8916195625460801
For min_samples_leaf = 3, accuracy = 0.8916195625460801
For min_samples_leaf = 4, accuracy = 0.8916195625460801
For min_samples_leaf = 5, accuracy = 0.8916195625460801
For min_samples_leaf = 6, accuracy = 0.8916195625460801
For min_samples_leaf = 7, accuracy = 0.8916195625460801
For min_samples_leaf = 8, accuracy = 0.8916195625460801
For min_samples_leaf = 9, accuracy = 0.8916195625460801
For min_samples_leaf = 10, accuracy = 0.8916195625460801
For min_samples_leaf = 12, accuracy = 0.8916195625460801
For min_samples_leaf = 14, accuracy = 0.8916195625460801
For min_samples_leaf = 16, accuracy = 0.8916195625460801
For min_samples_leaf = 18, accuracy = 0.8916195625460801
For min_samples_leaf = 20, accuracy = 0.8916195625460801
Best min_samples_leaf: 2
Best accuracy: 0.8916195625460801

In [16]:
#Post Prunning
full_tree = tree.DecisionTreeClassifier(random_state=42)
full_tree.fit(X_train, y_train)
path = full_tree.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas

# train our model for all alphas

trees = []

for alpha in ccp_alphas:
    model = tree.DecisionTreeClassifier(random_state=42, ccp_alpha=alpha)
    model.fit(X_train, y_train)

    trees.append((model, alpha))
best_acc = 0
best_alpha = 0

for model, alpha in trees:
    curr_acc = model.score(X_test, y_test)
    if curr_acc > best_acc:
        best_acc = curr_acc
        best_alpha = alpha

print(best_acc)

0.8930941263209634

In [24]:
#Combining all together
best_model = tree.DecisionTreeClassifier(ccp_alpha=best_alpha)
best_model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=np.float64(0.0004705248335210646))

In [25]:
y_pred=best_model.predict(X_test)
acc=accuracy_score(y_test, y_pred)
acc

0.8930941263209634

In [ ]:
from sklearn.metrics import f1_score